### ISSUE TITLE
Lazy map

### ISSUE THREAD

**Issue by pikawrex** [nus-cs2030/2122-s1#152]
I'm having some difficulties with lazy implementation of map, and i don't really understand how do the other suggestions (using Supplier, etc) work. Any advice would be great!

**Comment by JasonLCY-Temp** [comment]
I was really confused at the start as well on how to implement lazy mapping, but managed to finish the Lab eventually. I'll share some details of my own implementation and I hope that this information can help you progress with your own implementation in some way. It probably won't be very useful if you used another way of implementing your Logger object though.
The way i implemented my Logger was essentially reusing the Lazy class from the mini-project (So my Logger is essentially Lazy and I use the cache to represent the value stored in the logger), as suggested by a few others in previous discussions (Thanks for the tips everyone).

For lazy mapping, I first created a new Logger object 'newLog', a supplier of get() mapped with the input function was provided to the constructor. I used an ArrayList<Supplier<String>> for my log so for logging, the new log entry was a Supplier to a String.format(), with the pre-mapped value being this.get() and the post-mapped value being a get() called from newLog that was previously created (Because of the way the caching is implemented, the evaluation of the mapping is only done once ever inside newLog, every other call of get() should return the cache which is just a value/Optional of a value without having to evaluate the supplier, which bypasses the level 5 issue of double printing), then finally the method returns a new Logger that takes in a supplier of the newLog.get() and the updated log. So in the entirety of the map method, no get()s or maps are actually performed since every call of those methods are "delayed" behind a supplier. To then get the output needed to match the testcase outputs, I treated my toString() method as a terminal operation, and would call the get()s required there to ensure that everything is evaluated and ready for printing.

**Comment by pikawrex** [comment]
Thanks so much for your detailed reply! I re-implemented my Logger with Suppliers in mind, but i have some questions regarding the evaluation within newLog that i hope you could clarify:

What do you mean by "the new log entry was a Supplier to a String.format()" ?

I thought the idea of using ArrayList<Supplier> was to allow you to iteratively generate the outputs inside the toString() of Logger, but i'm interested in how you managed to evaluate the mapping inside newLog, if possible could you evaulate more?

**Comment by JasonLCY-Temp** [comment]
> What do you mean by "the new log entry was a Supplier to a String.format()" ?
My log is 'ArrayList<Supplier<String>>', so the log entry would be a 'Supplier<String>' (I used String.format to format it, but it is essentially just a String). The old/new values are simple get() calls and newLog.get() calls respectively, but since everything is behing the Supplier, nothing is actually evaluated inside the map method. 
Then in the toString method(), I would iteratively generate the outputs by calling get() on each Suppler present in the ArrayList, that get() would then trigger the original get() and newLog.get() calls to obtain the pre-mapped and post-mapped values.
Sorry if i misunderstood your question, hope this helps.

**Comment by pikawrex** [comment]
That makes sense, it helped loads, thanks!
