### ISSUE TITLE
Map 

### ISSUE THREAD

**Issue by brandonrhan** [nus-cs2030/2122-s1#165]
I am not sure about how to use supplier in map. If I use supplier.get() in map then it will still print out "add 1" . What other implementation should I make to prevent this happening?

**Comment by CedricPei** [comment]
stuck at lv5 also and the same question ......

**Comment by Eclipse-Dominator** [comment]
Don't call supplier.get() in map 👍. Leave all the getters to be evaluated last.
Basically make map and flatmap evaluate lazily. So for the case of this lab, the values are only evaluated when it is asked for specifically like in toString

**Comment by JasonLCY-Temp** [comment]
Essentially what Eclipse-Dominator suggested, make your map method lazy so that nothing is evaluated inside, in that situation the "add1" will never be printed because a supplier.get() will never be called on the add1 function since it is discarded after the test (since it returns sub1), you can refer to #152 where i detailed my own implementation of making Logger and mapping lazy and hopefully that can give you some ideas on how to proceed with your implementation.

**Comment by ReubenChay** [comment]
adding on to the previous 2 comments, you might struggle with updating the String log eg. "5 -> 6" when you do lazy evaluation. I faced this issue so thought i might share. You could consider cache-ing the values or a (personally) easier method was to create a Pair<T, String> class and have your supplier wrap around this, like Supplier<Pair<T, String>>. This way your supplier supplies you both the String and the value, but both lazily. Or you could use other methods im sure there are many other ways

**Comment by brandonrhan** [comment]
thanks guys I think i will rewrite everything using supplier as attribute

**Comment by ff1Zzd** [comment]
In my opinion, the supplier.get() should only be called in toString() in this lab. However, you can still perform get operation and update your data inside map, just wrap it with a supplier. Hope this can give you some idea!
