### ISSUE TITLE
Chaining map on Logger lazy implementation

### ISSUE THREAD

**Issue by zunedz** [nus-cs2030/2122-s1#167]
## Description:

I recognized that Codecrunch only has 1 test case to test the lazy implementation of ``` Logger```, so I'm not really sure whether or not my code is correct and I tried something like this:

```bash
Logger.<Integer>of(5).map(x -> {System.out.println("OK"); return x + 1;}).map(x -> x + 2);
```

How many times do you think "OK" is supposed to be printed and why?

**Comment by RussellDash332** [comment]
It should be only once.
The first mapping prints OK once it's mapped from 5 to 6.
Then, when it's mapped from 6 to 8, no side effect occurs.

**Comment by zunedz** [comment]
Alright thanks! so essentially the first mapper will be executed only once regardless of how many chainings you do? then I guess my implementation is still wrong LOL.

**Comment by cliftonfelix** [comment]
I was trying this test case and it printed two "OK".. So, I tried to use cache (which I previously didn't use as the test cases on CodeCrunch do not test this).

I submitted to CodeCrunch and CodeCrunch still accepts even though the cache is not private final (only private). Now I'm wondering how CodeCrunch determines whether it's okay to use private instead of private final because for the first few labs, IIRC I got some error warnings on CodeCrunch saying that attributes must be private final.

**Comment by upabove122** [comment]
I'm not sure whats the right way to do it, but shallow lazy let me passed this level. So only the first map is lazy. if there is 2 map, the middle map gets evaluated XD

@cliftonfelix URGH I was avoiding not doing private final for the life of me and this happens D:

**Comment by brandonrhan** [comment]
I think there should only be one, as your map function should return a new logger
