### ISSUE TITLE
Why do we need to lazy?

### ISSUE THREAD

**Issue by cindyangXQ** [nus-cs2030/2122-s1#178]
# Summary

Why can lazy solve the "sub1" testcase in level 5? 

## Description:

I found out that I didn't pass this testcase, so I made `test` do nothing but `return null`. However, the testcase still prints both "add1" and "sub1". So I thought the problem should be with the param list ?? which is very confusing. 

Then I read the discussions here and realized that this issue should be solved by lazy, but still I don't understand how lazy implementing `map` and `flatMap` is related to `test` at all.

**Comment by aexolate** [comment]
It is due to the fact that `five.map(x -> { System.out.println("add 1"); return x + 1; })` is passed as the parameter in the test function. This would have been processed before the code in your test function. So if your Logger .map() is not lazy, both add 1 and sub 1 will be printed regardless of what is inside test()

**Comment by cindyangXQ** [comment]
Thank u for the extremely clear explanation!
