### ISSUE TITLE
How does codecrunch determine which classes have cyclic dependency?

### ISSUE THREAD

**Issue by yeehaoo** [nus-cs2030/2122-s1#183]
# Summary
Hi friends, I'm a little confused on what's considered a cyclic dependency and what's not.

## Description 
For example, here codecrunch says I have a cyclic dependency (out of 45 total haha), could you give an example of which blocks are considered CDs? There are 2 dependencies according to CC, to Server and Customer. Is it due to the return Customer return type? Or calling Customer's methods? There isn't even anything referencing Server!
![Untitled](https://user-images.githubusercontent.com/23189791/140477540-ba0ff98a-caae-4a28-8e74-3e38671eb09f.png)

Thanks in advance!

**Comment by bingsen0806** [comment]
class A is considered to depend on class B if class A needs class B to compile. In your case you have a `List<Server>` in the parameter of `abstract Event execute`. You also return `Customer` in your `getCustomer()`. Without Customer and Server class, your Event class wont compile, because it doesn't know what is Customer type and List<Server>

**Comment by yeehaoo** [comment]
> class A is considered to depend on class B if class A needs class B to compile. In your case you have a `List<Server>` in the parameter of `abstract Event execute`. You also return `Customer` in your `getCustomer()`. Without Customer and Server class, your Event class wont compile, because it doesn't know what is Customer type and List

I see, thank you very much!
