### ISSUE TITLE
Level 2 final test case

### ISSUE THREAD

**Issue by ikaajj** [nus-cs2030/2122-s1#184]
# Summary

Got the error: incompatible types: no instance(s) of type variable(s) U exist so that Logger<? extends U> conforms to Logger<java.lang.Number> for the final test case for level 2

## Description:

Running Logger.<String>of("hello").map(g) alone works fine, but running Logger<Number> lognum = Logger.<String>of("hello").map(g) throws the error incompatible types: no instance(s) of type variable(s) U exist so that Logger<? extends U> conforms to Logger<java.lang.Number> . 
Can't figure out what I am doing wrong for my map function, would appreciate any help if anyone else got the same error and managed to fix it! Thanks!

## Screenshots

<img width="547" alt="Screenshot 2021-11-05 at 4 26 50 PM" src="https://user-images.githubusercontent.com/92254207/140480793-fe1457a0-bb89-4cfc-ad27-b560e8465e02.png">

**Comment by vvidday** [comment]
Is the return type for your map function `Logger<? extends U>`? map should return `Logger<U>`.

**Comment by brandonrhan** [comment]
I also think maybe should return a new Logger<U>. Since the error message says Logger<? extends U> cannot conform to Logger<java.lang.Number>.

**Comment by ikaajj** [comment]
Yes, the return type for my map function is Logger<? extends U>, I changed it to return Logger<U> instead, and now it is working! Thank you all! But, I don't get why would Logger<? extends U> result in an incompatible type error while Logger<U> doesn't?

**Comment by vvidday** [comment]
> Yes, the return type for my map function is Logger<? extends U>, I changed it to return Logger instead, and now it is working! Thank you all! But, I don't get why would Logger<? extends U> result in an incompatible type error while Logger doesn't?

Yup, like brandon said, if our return type is a wildcard, we cannot be sure what the return type will be.

E.g. Let's say our `U` is `Number`, so the return type is `Logger<? extends Number>`. So, our map function can return any subclass of Number, like `Logger<Number>`, `Logger<Integer>`, `Logger<Double>`, etc. We aren't sure of what exactly it will return.

So what type can we assign the returned object to? We cannot assign it to a `Logger<Number>` because the return type may be a `Logger<Integer>`. (because generic types are invariant, we cannot do `List<Number> list = new ArrayList<Integer>()` for example). We cannot assign it to a `Logger<Integer>` or `Logger<Object>` because it may return a `Logger<Double>`.

The only return type we can assign it to is `Logger<?>`. This is what java is implicitly assigning it to when you just call `Logger.<String>of("hello").map(g)`. i.e. the following code is ok for your original implementation:
```
Logger<?> lognum = Logger.<String>of("hello").map(g);
```
But assigning it to `Logger<Number>` fails because we can't be sure of the exact return type.

hope this helps!

**Comment by ikaajj** [comment]
ohhh, yes I understand it now! Thank you both!
