### ISSUE TITLE
Problem with flatMap output for level 3 

### ISSUE THREAD

**Issue by ZChenxin** [nus-cs2030/2122-s1#215]
Hello, how did you all keep track of whether or not to print the change logs when it comes to flatMap? I am having trouble not printing when only flatMap is called

I.e for test case
`five.flatMap(x -> Logger.of(x + 1)),`
My output is
` Logger[6] `
` 5 -> 6 `

Currently I am storing all the mapped and flatmapped values into a single array, and iterating through that array to print, which is likely the source of this issue. But I am not sure of a non-complicated way to fix it

**Comment by ChrisHo1341** [comment]
For flatMap, I think the test case shows that flatmap itself does not change the logs at all, in the other test cases, the log changes are due to the map operations done within the flatmap operations. So you the flatmap operation itself does not create new logs, but it DOES carry forward any existing logs.

**Comment by thojianxiong** [comment]
For me what I did was imagine flatMap adding the logs of the inputs of the logger it's flatMapping from and the logs from the Logger that is produced from flatMap's Function. Like @ChrisHo1341 said it does not actually create new Logs from the operations in a sense.

For my case it worked because the method "of" does not record any logs and only map records down the logs.
