### ISSUE TITLE
Unable to key in Unix password after opening Ubuntu (Windows User)

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2030/2122-s1#22]
# Summary

## Description 
I opened Ubuntu and managed to key in my Unix username. However, any keys i press after pressing enter at my username does not trigger. When I opened Ubuntu again, the following (screenshot) appeared and I cannot run sudo apt update. Additionally, just to clarify, am I supposed to run "sudo apt update" in the Windows Powershell or Unix?
Edit: I ran "sudo apt update" in the Windows Powershell and the 2nd screenshot is the result.

## Screenshots (if any): 
![Capture ubuntu](https://user-images.githubusercontent.com/88729540/129484262-6a07fea3-9839-4604-8a87-9dc2589a77e8.PNG)
![Capture windows powershell](https://user-images.githubusercontent.com/88729540/129484793-3c32cac2-9257-4225-be5e-d70398c94b33.PNG)

**Comment by RicharCd** [comment]
Yea, `sudo apt update` does go into the Ubuntu terminal. 

Currently, you are the root user.

Could you try listing all your users through
```
cut -d: -f1 /etc/passwd
```
and take a look if the username that you entered previously exists in this list? If not, you can create a new user through
```
sudo adduser USERNAME_HERE
```
and type in a username and password. There's additional prompts asking for your full name, room number, phone number, etc that you can just skip through. If you ever need to come back to add or change the info, you can do so through
```
sudo chfn USERNAME_HERE
```
Then, or otherwise if the user already exists, switch users with
```
su - USERNAME_HERE
```

The new user created may not have sudo privileges because it is not part of the sudo group. Executing privileged commands might cause you to see something like,
```
_user is not in the sudoers file.  This incident will be reported._
```
so you can switch back to the root user through,
```
su -
```
add it to the group by using
```
usermod -aG sudo USERNAME_HERE
```
It is generally not a good idea to work with Ubuntu as the root user, so remember to switch back to the new user created using the same `su - USERNAME` command.

**Comment by ketamethane** [comment]
I tried creating a new username, and the following popped up. The same issue happened. I cannot type anything into the password section.
![Capture ubuntu 2](https://user-images.githubusercontent.com/88729540/129486274-e542a034-f7c5-431d-9cbd-aa73e8ac0d2a.PNG)

**Comment by RicharCd** [comment]
Ah I understand, the password field is blanked out for your privacy. The actual password is being keyed, press enter after you've finished keying and you'll be prompted to retype the password. If both passwords are similar, you'll be allowed to continue.

**Comment by ketamethane** [comment]
Oh so that's why... thank you RicharCd :)
Though I'm not sure why privacy is necessary since I am the only one looking at the screen.
