### ISSUE TITLE
Difference Between map() And flatMap()

### ISSUE THREAD

**Issue by yueyin22** [nus-cs2030/2122-s1#222]
I'm still confused by this as I re-watched the lectures.

Can anyone explain with some simple examples?

**Comment by xaviertanwc** [comment]
If my interpretation is not wrong, I believe the simplest way to differentiate the 2 is that (1) mapping applies the function in the most literal way, whereas (2) flatmapping unravels the generic class before applying the function. 

Take Optionals for example. If I were to do Optional[5].map(x -> x + 1), the map literally takes the value (5) and replaces it with a (5 + 1). Hence, I would get an Optional[6]. If I were to do Optional[5].map(x -> Optional.<Integer>of (x + 1)), it would literally replace the (5) with an Optional[6]. Now I would have a nested Optional[Optional[6]], which is not ideal.

This is where flatmapping comes in, when you want to map to the same generic class but you don't want them to nest. So Optional[5].flatMap(x -> Optional.<Integer>of (x + 1)) would give me Optional[6].

**Comment by Irminrics** [comment]
Hello, you can also refer to #102 for some clarity.

**Comment by ChrisHo1341** [comment]
In the context of Optional (but I believe this can be generalized to other classes like streams), the difference between Map and flatMap is that map applies the function to the value within the optional and rewraps it in an Optional again, flatMap on the other hand, only applies the function to the value in the optional but does not rewrap it in another Optional.

I think alot of confusion arises because flatMap ONLY takes in functions that output an Optional itself as seen from the java API
![flatmap](https://user-images.githubusercontent.com/79920944/141223622-6169c6a4-acc8-4124-8f67-4c0fa0a9667c.PNG)

As you can see, you will basically only use flatMap when the function you want to apply to the value already produces an Optional, to prevent double wrapping.

**Comment by KeithPJX** [comment]
For a `map` of an `Optional` for example, you first retrieve the `data` from `Optional` then perform a `function` that returns a `non-Optional` on the `data`, it then wraps the output of function into an `Optional` and `map` returns this.

For a `flatMap` of an `Optional`, you first retrieve the `data` from `Optional` then perform a `function` that returns an `Optional` on the `data`. If you follow what `map` does here and wrap this into an `Optional`, you will end up with an `Optional of an Optional`. `flatMap` solves this by "flattening" the `Optional of an Optional` into just a single `Optional` of the output from the `function`.

This is the main idea of `map` and `flatMap` and it will follow for other implementations other than `Optional`.

**Comment by yueyin22** [comment]
I think i got it! Thanks!
