### ISSUE TITLE
Calculating normalizedMean() without helper class

### ISSUE THREAD

**Issue by tubting** [nus-cs2030/2122-s1#226]
Understand that a few discussions have already suggested passing in the stream into an array and then passing it into a helper class. Was wondering if it was possible to calculate the values for sum/min/max in the main class using Arrays.stream(streamArray).max().getAsInt() or could someone explain why we need a helper class? Thank you!

**Comment by ZChenxin** [comment]
Yes, I managed to used arrays and did not use a helper class, but using a helper class would make your code much more readable

**Comment by malwaregarry** [comment]
Hi, the purpose of the helper class is to do a multiple mappings on the same element at the same time instead of just one-to-one, and an array can also accomplish this.
With our without the helper class, calculating the sum/min/max should not be done with the the `.max()` / `.min()` methods as this would mean that you have exhausted the stream. They should instead be calculated at the same time using `.reduce()` after the mapping has been done.

**Comment by lulucopter** [comment]
Agree with the above comment. Using any terminal operation will "process" the stream, and a processed/reduced stream cannot be processed again. And streams doesn't have any method to "copy" themselves, thus the helper method seems to be the only way to solve this.

**Comment by tubting** [comment]
thanks for the help everyone!
