### ISSUE TITLE
Level 5 tips 

### ISSUE THREAD

**Issue by Devvynneo** [nus-cs2030/2122-s1#232]
Hi! 

In level 5 I realised that map has to be lazy,
if map is lazy, this means that we cannot use supplier.get() in the method until the return statement right? 

However, I'm a bit stuck on the how do we add onto the list of logs that keeps track of our changes? 
In my map method, I store the old value and new value as strings in a list so that the change log can be carried on, but if we cannot use mapper.apply(supplier.get()) to get the new value then how do we update the list of logs? 

Thank you!!

**Comment by RussellDash332** [comment]
Everytime you map, add the supplier of the new log line instead of just the line. Once you call toString(), open all the suppliers using .get() method.

**Comment by jerylseow** [comment]
You can use `supplier.get()` within the map method. It is still lazy if you wrap this `supplier.get()` within another Supplier. For example, `Supplier<T> s = () -> { T newValue = mapper.apply(supplier.get()); ...};` will not be evaluated until needed.

**Comment by brandonrhan** [comment]
For the log, u could use an ArrayList of Supplier to store all your suppliers. When u map() or flatmap(), copy the old list and add the new supplier into the list. Just move the supplier.get() part into toString(). Take note every supplier should only be get() once, otherwise will cause double print of "sub1".
