### ISSUE TITLE
About the jar file

### ISSUE THREAD

**Issue by yuyanjulia** [nus-cs2030/2122-s1#243]
There was a bug in my `BusRoutes.java` and I was trying to find it. Hmmm I actually found it and changed. Then I did `echo "16189 Clementi" | java -jar level3.jar` again but it was still the same output. So I thought there was some other bug around and I went searching for it for a long time. It turns out I have to `jar uf level3.jar *.class` again after I updated my code. I didn't know ;-; 
I am wondering why for the normal code, we can just run it without always `javac *.java`, but it doesn't work for jar in this lab? Is it something to do with "update the given jar file"?

**Comment by RussellDash332** [comment]
When you compile all files, it will generate the class files for all Java files, then when you update the jar, since we're using `*.class`, it will also update the async version of the unnecessary classes, making the whole jar to run a synchronous program. In that case, instead of `jar uf level3.jar *.class`, try changing `*.class` to only the classes that you modifed on that level and before that, but not after it.
