### ISSUE TITLE
Did I manage to install Java Development Kit?

### ISSUE THREAD

**Issue by ketamethane** [nus-cs2030/2122-s1#25]
# Summary
Put a summary of the problem here

## Description 
As per what the screenshot shows. I entered the [sudo] password but I'm not sure if I manage to install the JDK.

## Screenshots (if any): 
![Capture JDK](https://user-images.githubusercontent.com/88729540/129685252-e3a4bbda-bfd1-4b7b-9303-6508e3017fa9.PNG)

**Comment by Justinhoejj** [comment]
Verify JDK installation: A quick search of the web will reveal multiple ways to [check](https://www.quora.com/How-do-I-know-whether-jdk-is-installed-in-my-computer-or-not
) if JDK is installed correctly.

Error message at last command: The last command is an error with admin permissions? Found a [webpage](https://www.tecmint.com/fix-user-is-not-in-the-sudoers-file-the-incident-will-be-reported-ubuntu/
) that explains the problem.

Hope these links are helpful.

**Comment by ketamethane** [comment]
Okay, I realised that by previously changing the default user in Ubuntu, I could not install using the sudo command. I changed the default user back to root and proceeded with the above sudo apt install step again, getting this result.
![Capture](https://user-images.githubusercontent.com/88729540/129857754-a7802cc1-cdc2-41bd-9c1f-a690a73698cd.PNG)
Upon looking at my list of window programmes, I realised that I previously installed JDK 11.0.11 ( which is not what we are using for this module) so I uninstalled it.
I proceeded to repeat the setting up of Java steps and came across this instead.
![Capture](https://user-images.githubusercontent.com/88729540/129858504-02696758-d977-4c63-823a-48f5afb55f8e.PNG)
The problem now is I only have this version of Java in my window programmes.
![Capture](https://user-images.githubusercontent.com/88729540/129858712-065ee3d9-139d-4b43-ba40-aa46b45e6e6c.PNG)

**Comment by RicharCd** [comment]
Hello ketamethane!

I noticed you're the same person that asked the question regarding password not appearing and the setting up of a new user account. Can I verify if you have successfully completed the
```
usermod -aG sudo methane
```
command? If not, you could take a look [here](https://github.com/nus-cs2030/2122-s1/issues/22#issuecomment-899078826), from the 5th line onwards, to add methane into the the sudoer's group. Alternatively, the website linked by Justin provides an alternative way to add methane into sudo.
```
adduser username sudo
```
It's not advisable to do things in root because, with root having unlimited power, there's a risk you might do something unintended, as well as it being a security hazard. A user with sudo privileges would be a better choice. Initially you may want to go there to add, delete or elevate users but most of the time you can just lock the root user account, since using `sudo` can effectively achieve most things.

Additionally, the Java that is installed in your Windows isn't the same as the Java that has been installed in Ubuntu! You can query the Java version through
```
java --version
```
if there is output with the correct version, i.e. something like `openjdk-11.0.8` (the one reccomended by the guide), then java should be installed properly. Here's mine
```
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.8+0-adhoc.centos.jdk11u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.8+0-adhoc.centos.jdk11u, mixed mode)
```
this is different from that in my Window's system,
```
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```
I don't think it was installed properly, given that methane doesn't have sudo rights, as in the first pic. In the second picture, I actually think you succeeded but you're looking at the Java you have in your Windows system and not Ubuntu.

**Comment by ketamethane** [comment]
Hi RicharCD! Apologies for the late reply. Yes, I've managed to add my username into the sudo, and I re-installed Java.
Thanks for the help, Justinhoejj and RicharCD!
