### ISSUE TITLE
Functors and Monads

### ISSUE THREAD

**Issue by Twars2** [nus-cs2030/2122-s1#261]
Towards the end of Lecture 11, we slightly touched on Functors and Monads where they are wrappers of values with contexts. Since Optional is both a functor and a monad what is the practical difference between a Functor and a Monad (ie when do we use Functors, Monads, or both)?

My second question is if Logger and pa2's Rand is both a functor and a monad since they have a map a necessary function of Functor and flatMap a necessary function of Monad. Furthermore, the mapping in pa2 is clearly associative as map(..).next() and next().map(...) yields the same result.

**Comment by cheeheng** [comment]
First question
If I have not mistaken, the functor corresponds to the map method while a monad corresponds to a flatMap method in Java's Optional. We use map if we want to map a value within a context to another value within a context via an input function. 

Suppose the map function maps a value within a context to another value within the context in the context (something like a box within a box). Then it would be cumbersome having to get rid of one layer. Hence, we use flatMap to automatically get rid of that extra layer. That would be the monad.

I hope I understood it correctly. Please correct me if I am wrong.

**Comment by cheeheng** [comment]
Second question
I think the answer is yes for Rand because all the functor and monad laws are satisfied.

For Logger, I think this is a counterexample to the identity law in functors (Level 2), as in ```logger.map(x -> x)``` doesn't exactly give back ```logger```, because the extra line of output needs to be stored in the resulting object itself, in other words, the underlying logs are different. 

![image](https://user-images.githubusercontent.com/13196670/141926176-4dc9d263-e337-4231-adbf-a1c7cd81be75.png)

According to the definition of the .equals() method (Level 4), both the logs and the underlying object need to be the same. Hence, Logger is almost a functor but not quite.

However, Level 4 mandates that monad laws must be satisfied for Logger because the sample testcases test for all the monad laws.

Hence, Logger should be a monad but not exactly a functor.
