### ISSUE TITLE
Test case 3_3 for project

### ISSUE THREAD

**Issue by satsuma42** [nus-cs2030/2122-s1#278]
So my code is able to pass test cases 3_1 and 3_2, but not 3_3. Does anyone have a similar experience? Seems that it's a series of cascading errors resulting from one miscalculation or misallocation midway through the event. My guess is that because of overlapping Serve and Wait events, my Servers are not drawing rest time in chronological order. Would appreciate if anyone could shed light on the test case itself as well!

![image](https://user-images.githubusercontent.com/65331658/142210099-05c51521-3564-4d61-acff-a0cd043781fe.png)

**Comment by JordanChua** [comment]
I had a similar problem where the queue of my Server wasn't really updating properly which resulted in the error you got above. If we look at the test case we see that at the exact point of time when Customer 14 arrives, Server 1 is currently resting and there are 2 people in the queue {Customer 10 and Customer 13}. When Customer 14 sees this he should rightly wait at Server 2 since the queue is full, so maybe you could try debugging by printing what the queue for Server 1 is like when Customer 14 arrives and check if both Customer 10 and 13 are in the queue, which I think may not be the case for your output :)

**Comment by yuyanjulia** [comment]
So when your server is resting, make sure the waiting customers are all accounted for when you calculate the queue length. In this case, server 1 has 2 customers in the queue so incoming customer has no more places to queue. Then customer 14 goes to server 2.

**Comment by satsuma42** [comment]
@yuyanjulia @JordanChua Thanks for your help! I honestly thought this was because of allocations of rest time, which would be so much harder to solve for! Yall saved me so much time barking up the wrong tree!
