### ISSUE TITLE
Simulator: Cyclic Dependencies Detected

### ISSUE THREAD

**Issue by cindyangXQ** [nus-cs2030/2122-s1#281]
# Summary
I have Arrival -> Serve -> Done -> Serve in my design. The last Done -> Serve is to see if there are any customers in queue, and if yes Serve them. I don't seem to find a way to avoid this cycle here. What is your design?

**Comment by JordanChua** [comment]
One way I bypassed this was to handle this in my Simulator Class(or Main class thats fine as well).  The main idea here is that  our Done Event would simply return nothing in my Done class. Instead, when I poll my Done Event from my PriorityQueue, I will create a new Serve Event and add that to my PriorityQueue 

This bypasses the cyclic dependency since my Done Event when executed technically does not return a Serve Event. Instead, when I do poll() on my PriorityQueue and I get a Done Event, we will recognise this as a Done event type and proceed to add a new Serve Event to the PriorityQueue using the customer taken from the waiting queue. This is essentially what you are trying to do, but without the cyclic dependency since we are handling it in our Simulator/Main class :)

**Comment by ZChenxin** [comment]
For me I had the final Done event not return anything as well, but instead free up the server that is “Done”

I also had a WaitServe event as an intermediate between wait and serve. Every customer that enters a queue with Wait will have a WaitServe event added to the PriorityQueue as the next event with the service end time of the server assigned to the customer. The WaitServe event then checks if the server is free when executed. If not, another WaitServe event is added with an updated end time. If yes, then a Serve event is executed instead. So there isn’t a cyclic order of Serve -> Done -> Serve. Instead it’s a straight line from Wait -> WaitServe (possibly repeated) -> Serve -> Done 

Having an intermediate event is also quite useful in later levels I think

**Comment by weiquany** [comment]
Hi Cindy, my way was to have Arrival -> Wait (repeat if necessary) -> Serve -> Done. A customer in the server's queue will have a WaitEvent at the same time as the DoneEvent such that it will be evaluated right after a Done event. WaitEvent will return another WaitEvent if the server is resting or the customer is not going to be served next. The server itself will keep track of its rest and its next available time which can be obtained using get.

**Comment by kxshxsh** [comment]
I had a slightly different approach! My design follows the flow: Arrive -> (wait) -> Serve -> Done -> Rest -> Exit;
When I poll an Exit Event from my Priority Queue, I don't further add anything back into the PQ for the event flow of this particular customer.

**Comment by teominghuang** [comment]
Hihi,
My design allows for 2 different event flow:
1. arrive -> wait -> serve -> finish serving -> rest -> complete  _AND_
2. arrive -> serve -> finish serving -> rest -> complete 

I had the same thing happening to my design when I forced the completion to check if there exists a queue and create a Serve event. However, instead of using the completed event to create a Serve event, I relegated that task to my simulator to create a Serve event (by checking event type whenever I poll from the PQ). That way, it will not result in a cyclic dependency since my Completion event is no longer used in creating a Serve event. 

All the best!!

**Comment by CalebLee** [comment]
I did similar to Jordan, so the flow is:
Arrive -> (Wait) -> Serve -> Done (or Done Resting)

Importantly, you will need a way to differentiate between the different types of Event so that your Simulator recognises the Done Event. Your Simulator will then manually add a new Serve Event to the PriorityQueue to circumvent the cyclic dependency.

To avoid having to use instanceof to identify the Done Event, you might find this post on [recommendation to use enums](https://github.com/nus-cs2030/2122-s1/issues/275) helpful. Hope this helps!

**Comment by cindyangXQ** [comment]
Thank you all for the replies! I decided to go for what Jordan mentioned (cuz it causes the least trouble in my case) and problem solved!
