### ISSUE TITLE
Level 4 testcase 4_0 why customer 16 join server 1

### ISSUE THREAD

**Issue by optionalemon** [nus-cs2030/2122-s1#291]
## Description 
I am a confused of why customer 16 is joining server 1?

## Screenshots (if any): 

<img width="261" alt="Screenshot 2021-11-18 at 18 23 51" src="https://user-images.githubusercontent.com/86706511/142397673-957cfa43-9f0c-4a46-bb8b-fef526f56c27.png">

The way I decide which queue each customer shd join is to find out the actual time this customer can be served (+ not exceeding the max queue length), and I think 16 joining server 2 makes it being served must faster than it joining server 1? 
If this implementation is wrong, how do we decide which queue should the customer join? 

<img width="262" alt="Screenshot 2021-11-18 at 18 24 20" src="https://user-images.githubusercontent.com/86706511/142397756-38a1782c-1acb-4979-a935-407f9b35a693.png">

**Comment by JordanChua** [comment]
The way the Customer decides where to go is basically done in 2 steps:

Step 1: He first scans from the 1st to the last Server and check if anyone is available to serve him

Step 2: If every Server is currently serving someone/resting, then he starts scanning from the 1st server to the last to check if there is any space in the queue for him to join. In the testcase, only Customer 13 is in the queue of Server 1 so Customer 16 sees this and recognises that there is still space in the queue for him to join, that's why he will wait at Server 1. He doesn't choose the Server based on how fast he will get served( although in level 5 a greedy customer will choose based on how many people there are in the queue)

**Comment by optionalemon** [comment]
> The way the Customer decides where to go is basically done in 2 steps:
> 
> Step 1: He first scans from the 1st to the last Server and check if anyone is available to serve him
> 
> Step 2: If every Server is currently serving someone/resting, then he starts scanning from the 1st server to the last to check if there is any space in the queue for him to join. In the testcase, only Customer 13 is in the queue of Server 1 so Customer 16 sees this and recognises that there is still space in the queue for him to join, that's why he will wait at Server 1. He doesn't choose the Server based on how fast he will get served( although in level 5 a greedy customer will choose based on how many people there are in the queue)

Oh, alright!! I think im overthinking about this then, will close this issue when I have corrected my mistake! Thank you so much!
