### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: cs2030/simulator/EventComparator

### ISSUE THREAD

**Issue by tubting** [nus-cs2030/2122-s1#299]
Facing this issue even though my EventComparator class is in the same folder as simulator and have imported all the classes into main... any ideas why this happening? Thanks in advance!

**Comment by albertsutz** [comment]
This is because your EventComparator should not be accessed from outside the package. (It is not public class right?) 

all of your MainX.java is outside the cs2030.simulator package also, so you cannot access anything except the Simulator (the only one that is public)

**Comment by tubting** [comment]
> This is because your EventComparator should not be accessed from outside the package. (It is not public class right?)
> 
> all of your MainX.java is outside the cs2030.simulator package also, so you cannot access anything except the Simulator (the only one that is public)

oh yes I did not reference the comparator in my main classes and made only the simulator public so im not sure what went wrong

**Comment by CalebLee** [comment]
You shouldn't need to import all the classes into Main, only the Simulator class with `import cs2030.simulator.Simulator`.

Do check that your Main-s are not creating the PriorityQueue themselves, since that means they are also accessing the EventComparator. Other possible issues might be the naming of the EventComparator file, or just try re-compiling the EventComparator file on its own first before compiling Simulator. Hope this helps!

**Comment by tubting** [comment]
Thanks for all the suggestions everyone!
