### ISSUE TITLE
Project Lv 5 ideas

### ISSUE THREAD

**Issue by PokezardVGC** [nus-cs2030/2122-s1#314]
hi guys, need some help coming up with a design plan for Lv5. 
Thoughts on this process and if also possible, share how u tackled this Lv? Tkx!!
Quote from the Qn: 
"It is also worth noting that the service time cannot be generated together with the arrival time as each customer is created before the simulation starts since the nth customer to arrive might not be the nth customer to be served! Although this might entail passing the RandomGenerator along with the Customer. This need not be so! Hint: Think Lazy..."

1) gen all the customers with no service time 1st in array or smt 
2) then sort them by their arrival times 
3) then attach the service time to each of them before putting it into pq as an arrival event

4) gen out the rest time ltr once a done event is printed (should be same implementation as Lv3)

Current implementation of server, any way of making use of this for "Lazy"? (Edit: restTime attribute is no longer used, now stored as an array of timings since Lv3)

![image](https://user-images.githubusercontent.com/71965541/142732569-93ebe30e-11e3-4aa3-995a-3243b241c43b.png)

**Comment by hewliyang** [comment]
If you initialize the customers according to the procedure described in the problem statement, I think they should already be sorted by arrival times

> start the simulation by generating the first customer arrival event with timestamp 0
if there are still more customers to simulate, generate the next arrival event with a timestamp of T + now, where T is generated with the method `genInterArrivalTime();`

for (3) and (4) I think you can make it work depending on your implementation. For me I only generated the service/rest times when I needed to update my event times

**Comment by Benjamin-Sim** [comment]
> hi guys, need some help coming up with a design plan for Lv5. Thoughts on this process and if also possible, share how u tackled this Lv? Tkx!! Quote from the Qn: "It is also worth noting that the service time cannot be generated together with the arrival time as each customer is created before the simulation starts since the nth customer to arrive might not be the nth customer to be served! Although this might entail passing the RandomGenerator along with the Customer. This need not be so! Hint: Think Lazy..."
> 
> 1. gen all the customers with no service time 1st in array or smt
> 2. then sort them by their arrival times
> 3. then attach the service time to each of them before putting it into pq as an arrival event
> 4. gen out the rest time ltr once a done event is printed (should be same implementation as Lv3)
> 
> Current implementation of server, any way of making use of this for "Lazy"? (Edit: restTime attribute is no longer used, now stored as an array of timings since Lv3)
> 
> ![image](https://user-images.githubusercontent.com/71965541/142732569-93ebe30e-11e3-4aa3-995a-3243b241c43b.png)


For point 1 and 3, since you already have a `Supplier` for `serviceTime` in `Customer`, you can simply store the store the output of `genServiceTime()` in it and only evaluate it when you're about to serve the customer. That's lazy evaluation.

For point 2, the way arrival times are generated is to add the generated value to the "current" time. So when generating customers, each customer will have a "later" arrival time than the one before it. So there shoudn't be any need to sort since they all have arrival times in ascending order.

For point 4, I believe your method should work. You're simply generating the rest times as you go along instead of reading them from a given input.

**Comment by PokezardVGC** [comment]
Currently facing some logical errors with my implementations. To update my server's mostAvailableTimings, when I create a new Wait Event (ie: when someone joins the queue), the server's mostAvailableTiming will add the service time of the customer in front. Anyway to work around this?

**Comment by thojianxiong** [comment]
@PokezardVGC 
For my implementation what I did was add the customers to the server's queue if there are no available servers at the point in time, and create the Wait event simultaneously. At this point, I do not determine the time the customer will be served and simply add this customer to an available queue.
I also had a Server Return event that happens after each Server Rest event, which checks whether there is any customer in its queue before dishing out any Serve Event. 
I found it easier to make a new Serve Event only when the server is actually free to serve the customer and that customer is next in line. The new Server will also be created only at the point of service hence the Server end time should be the most updated

Hope this helps!

**Comment by satsuma42** [comment]
> Currently facing some logical errors with my implementations. To update my server's mostAvailableTimings, when I create a new Wait Event (ie: when someone joins the queue), the server's mostAvailableTiming will add the service time of the customer in front. Any way to work around this?

Same as @thojianxiong! Just because we have to present our final product in chronological order doesn't mean we necessarily need to process Events in that order. The length of my Wait events is also retroactively determined after the Rest time is determined for each Server. That way we can use a Supplier or some other method call to provide an end time without worrying what it is.

**Comment by SW-bza** [comment]
I only generated ServiceTime when SERVE event is created, I didn't put them together with Customers. I just put dummy value of ServiceTime as 1 when I created a list of customers with arrivalTimes. Technically we do not need ServiceTime when we create customers kinda? So I delayed the generation and input of ServiceTime until I call serve(customer, startTime, serviceTime) method in Server, when the SERVE event is called. 

For REST, it was pretty similar to Level 4, I just replaced the restTimes List with genRestPeriod() and replace? the if statement with restProbability being less than genRandomRest()

**Comment by JavierTham** [comment]
You're on the right track of using Supplier for the serviceTime. For me, I didn't use a dummy variable during the initial creation of a Customer (`Simulator` class in my case), instead I created an overloaded `Customer` constructor that takes in a `Supplier<Double> serviceTime` and passed in the random generator.

Something like: `new Customer(id, () -> rg.genServiceTime(), arrivalTime)`

> 2\. then sort them by their arrival times

As stated by some above, you don't actually need to sort them by arrival time as they're alr sorted when you generate them.

> 3\. then attach the service time to each of them before putting it into pq as an arrival event

I can add Arrive Events into the pq without knowing the serviceTime because I only need to use it in my Serve Event (for my implementation). Not sure how you implemented it though.

**Comment by DankaiAndrew** [comment]
for my implementation, i did not use supplier. Instead I store customer serve time in an array and set all customers' servetime to -1 at the initialization stage. and I have two arraylist, one for manual server, and one for self counter
so my logic is:
1. Create Customer while set all serve time to -1, and check whether we should set them to greedy.
2. add all customers to ArriveEvent, add ArriveEvent to PQ
3. whenever dequeue is ArriveEvent, we check our two array, if both array if full while all servers' queues are full, we arrange a LeaveEvent; else we choose a server currently available or has the least ppl(if it is greedy, otherwise just do it like previous level) in their queue and add a ServeEvent along with it.
4. if dequeue is serveEvent, we generate the   service-time, and set customer service time with this value. then we arrange a doneevent
5. if dequeue is DoneEvent, we check whether rest is needed, if not we add a RestEvent with rest time 0, else generate a RestEvent with that rest time
6. if dequeue is RestEvent, we check whether there are customers inside the server queue, if so, we arrange a new serve event with the customer.

**Comment by PokezardVGC** [comment]
Thanks for all your inputs guys, appreciate it! :)

**Comment by PokezardVGC** [comment]
For the greedy customer, does he choose the queue with the least amount of people queuing or the one with the least wait time?

**Comment by DankaiAndrew** [comment]
> For the greedy customer, does he choose the queue with the least amount of people queuing or the one with the least wait time?
 least amount of people queuing

**Comment by PokezardVGC** [comment]
thx @DankaiAndrew

**Comment by PokezardVGC** [comment]
Thanks for all your help people, finally done with the project less white space indentations
