### ISSUE TITLE
Returning the length of a collection of string

### ISSUE THREAD

**Issue by mewrion** [nus-cs2030/2122-s1#319]
# Description
For questions where I have to use a stream of strings and find the length of the strings, why is it I have to use the combiner argument in order to return an integer?
## Topic:

Specific Topics this question is related to (If Any)

## Screenshots

Screenshots (if any)

**Comment by e0559198** [comment]
There are three versions of reduce in Streams. You can see from this 2 parameter reduce() function that everything is type T. 

reduce(T identity, BinaryOperator<T> accumulator)

This means the accumulator can only handle type T and return type T. It can't be used because you in your question, you probably would be using a integer and string type. Therefore we need to use this instead

reduce(U identity, BiFunction<U,? super T,U> accumulator, BinaryOperator<U> combiner)

**Comment by mewrion** [comment]
Thank you!!
