### ISSUE TITLE
Test Case 5_12

### ISSUE THREAD

**Issue by wjingen** [nus-cs2030/2122-s1#320]
# Summary
Hi all,

Debugging my Level 5 for Project and encountered an error for test case 5_12. Am wondering if anyone has the inputs for this test case so I can debug on my terminal. Thanks!!

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/74229021/142755222-7db5ab00-0418-4624-a2e0-d0d7f1eb374b.png)

**Comment by JordanChua** [comment]
Someone posted the link for the test case here : https://github.com/nus-cs2030/2122-s1/issues/170#issuecomment-961910252

Anyways for this testcase looking at the intended output at the point that 11(greedy) arrives there are 2 people in the queue for Server 1, 1 person in the queue for Server 2 and 1 person in the queue for the Self-Check counters. Since he is a greedy customer he will recognise that Server 2 and the Self-check counters both have the least number of customers in the queue, but he chooses the smallest ID to go to so he will go to Server 2's queue in this scenario. (he starts scanning from Server 1 and so on)

Since your output prints "11(greedy) leaves", I'm guessing there could be some problem in how a Greedy customer selects which queue to go to. In my case I scanned through the number of people in all the queues, stored the minimum number of people in all the queues as a value and compared it to the number of people in the queue for each Server/Self-Check starting from the smallest ID, so you could start debugging by checking how you implemented it :)

**Comment by wjingen** [comment]
> Someone posted the link for the test case here : [#170 (comment)](https://github.com/nus-cs2030/2122-s1/issues/170#issuecomment-961910252)
> 
> Anyways for this testcase looking at the intended output at the point that 11(greedy) arrives there are 2 people in the queue for Server 1, 1 person in the queue for Server 2 and 1 person in the queue for the Self-Check counters. Since he is a greedy customer he will recognise that Server 2 and the Self-check counters both have the least number of customers in the queue, but he chooses the smallest ID to go to so he will go to Server 2's queue in this scenario. (he starts scanning from Server 1 and so on)
> 
> Since your output prints "11(greedy) leaves", I'm guessing there could be some problem in how a Greedy customer selects which queue to go to. In my case I scanned through the number of people in all the queues, stored the minimum number of people in all the queues as a value and compared it to the number of people in the queue for each Server/Self-Check starting from the smallest ID, so you could start debugging by checking how you implemented it :)

OK I finally passed CodeCrunch after debugging for half an hour. Time to start studying for finals LOL. Thanks Jordan!
