### ISSUE TITLE
Final or effectively final error only inside class

### ISSUE THREAD

**Issue by RussellDash332** [nus-cs2030/2122-s1#336]
![image](https://user-images.githubusercontent.com/63991775/142878291-e0da8f80-742c-40d8-95f7-1d8f355ce3e5.png)
The insight came from the 2021S1 final paper. Just wondering it doesn't throw the error when it's a jshell line on it's own.

**Comment by aanghs22** [comment]
Hi! I think prof mentioned something like this in lecture 9, slide 10/11. 
Basically, you can't mutate client-side states inside any local class. Lambdas and anonymous inner classes declared inside any method are local classes.

In your screenshot, when that line of code `IntStream...` is declared within the `class X`, we can see that `s` was previously declared `int s = 0` before it's used in the lambda function `x -> s++`.  

As the lambda `x -> s++`, a local class, references the `s` declared above enclosed within `class X` that isn't declared as final, it doesn't work out! Because local classes can only access variables that are explicitly declared final or effectively/implicitly final (i.e. one that doesn't change after initialization). In this case, the `s` isn't explicitly final and neither is it implicitly final cos the lambda increments s.

Whereas if you input the `IntStream....` line as a single line in shell, there's no previous declaration of s so this error doesn't pop up. 

So far this is what I understand haha but I might have interpreted it wrongly, please correct me if I'm wrong!

**Comment by RussellDash332** [comment]
> Hi! I think prof mentioned something like this in lecture 9, slide 10/11. 
> Basically, you can't mutate client-side states inside any local class. Lambdas and anonymous inner classes declared inside any method are local classes.
> 
> In your screenshot, when that line of code `IntStream...` is declared within the `class X`, we can see that `s` was previously declared `int s = 0` before it's used in the lambda function `x -> s++`.  
> 
> As the lambda `x -> s++`, a local class, references the `s` declared above enclosed within `class X` that isn't declared as final, it doesn't work out! Because local classes can only access variables that are explicitly declared final or effectively/implicitly final (i.e. one that doesn't change after initialization). In this case, the `s` isn't explicitly final and neither is it implicitly final cos the lambda increments s.
> 
> Whereas if you input the `IntStream....` line as a single line in shell, there's no previous declaration of s so this error doesn't pop up. 
> 
> So far this is what I understand haha but I might have interpreted it wrongly, please correct me if I'm wrong!

Thanks for the explanation! I actually forgot to include the line `int s = 0` in the screenshot :D

**Comment by aanghs22** [comment]
> 

Whelps hahaha 

HMMMM I think the explanation kind of still applies? Lambda functions only require local variables to be declared as final or effectively final. The use of non- final/effectively final variables that aren't local variables is fine iirc. I'm assuming `int s = 0` was declared as a separate line in jshell and not within a class with the `IntStream` line so if I'm not wrong it's not considered a local variable.

![Screenshot 2021-11-22 at 11 07 00 [https://www.baeldung.com/java-lambda-effectively-final-local-variables](PM](https://user-images.githubusercontent.com/63781664/142885131-daf3c12e-d24d-4b6d-a480-4860e8ed3451.png))

**Comment by RussellDash332** [comment]
> 

LGTM! My case is the global scope while your case is the nonlocal scope. Both are fine :)

**Comment by RussellDash332** [comment]
> Hi! I think prof mentioned something like this in lecture 9, slide 10/11. Basically, you can't mutate client-side states inside any local class. Lambdas and anonymous inner classes declared inside any method are local classes.
> 
> In your screenshot, when that line of code `IntStream...` is declared within the `class X`, we can see that `s` was previously declared `int s = 0` before it's used in the lambda function `x -> s++`.
> 
> As the lambda `x -> s++`, a local class, references the `s` declared above enclosed within `class X` that isn't declared as final, it doesn't work out! Because local classes can only access variables that are explicitly declared final or effectively/implicitly final (i.e. one that doesn't change after initialization). In this case, the `s` isn't explicitly final and neither is it implicitly final cos the lambda increments s.
> 
> Whereas if you input the `IntStream....` line as a single line in shell, there's no previous declaration of s so this error doesn't pop up.
> 
> So far this is what I understand haha but I might have interpreted it wrongly, please correct me if I'm wrong!

Also you are correct, this slide answers it.
![image](https://user-images.githubusercontent.com/63991775/142911179-dcf7efa5-f761-42a6-9467-2b59df18c61f.png)


Not closing this issue so others can see this too.
