### ISSUE TITLE
Compile Time Error or Run Time Error?

### ISSUE THREAD

**Issue by cadencjk** [nus-cs2030/2122-s1#350]
Saw this question in one of the PYPs but there is no answer key.

![image](https://user-images.githubusercontent.com/63772723/143017162-6754527a-96c1-4cc9-a4f8-3aaf005c1dd1.png)

After running in jshell, this error appears.

![image](https://user-images.githubusercontent.com/63772723/143017418-48391e7e-1214-470d-a0d4-0ab2b0d7c2e9.png)

Is this considered as a compile time error or a run time error? Technically it compiles after running javac on it, but it does not return an Exception unlike the other run time errors we have seen.

**Comment by hingen** [comment]
Its a compile time error. The error occurs when u run the code `foo(1.0, 2.0)`. If you try to compile, the following code, ull get the error.

```java
class A {
    public static double foo(Double x, Double y) {
        return x + y;
    }

    public static double foo(double x, Double y) {
        return x - y;
    }

    public static double foo(Double x, double y) {
        return x * y;
    }

    public static void main(String[] args) {
        foo(1.0, 2.0);
    }
}
```

Since jshell interprets code as it comes, it's kind of compiling the code you submit then running it. Thus not all errors produced by jshell is runtime error.

**Comment by cadencjk** [comment]
Oh I get it, thank you!
