### ISSUE TITLE
How do you guys debug on vim/jshell in CS2030S?

### ISSUE THREAD

**Issue by UnwilledTangent** [nus-cs2030/2122-s1#59]
I'm used to having IDEs, whereby I can set breakpoints, go through the code line by line, and look at the different variables to see where my problem is.

I google searched ["debugging in Vim"](https://stackoverflow.com/questions/3536600/do-you-debug-c-code-in-vim-how) and ["debugging in jshell"](https://stackoverflow.com/questions/53703277/debugging-with-jshell), but they told me to install some plugin (which I assume it can't be used in Practical Exams), and that jshell does not have debugger support, and is not intended to be an IDE.

So what should I do to debug? Do I have to resort to System.out.println("flag 1"); everytime I pass through that particular line of code that I want to test? Thank you so much in advance!

**Comment by zunedz** [comment]
Most of the time I only rely on `javac` to debug my code if there's a compilation time error. Other than that, I believe the only way to debug is to use: 
```java 
System.out.println(String.format("var1: %s var2: %s", var1, var2));
```

since we're not allowed to use any extensions or plugins in PA or labs.

**Comment by qindalim** [comment]
Hi! I mainly use System.out.println() to test my code and debug. You can insert them at strategic points of the code to observe code patterns or check on the execution of a particular chunk of code. 

1) System.out.println("Executed") to show if a certain chunk of code has been executed - good for checking if else conditions, usually placed right after if clause
2) System.out.println(variable) to look into the variable and print it out - good for checking arrays and lists, or to observe the change in variables after every for loop, usually placed as the first and/or last line of for loop

These are just some of the ways that I use to debug my code, and it has been very helpful for my test and project. Happy to hear other methods out there!

**Comment by taymila** [comment]
For debugging codes that involves data structures like Arrays and Arraylist , I feel that printing out the arrays using the build in method  `toString()` is useful.
However sometimes depending on objects within the object, it is useful to write a separate method that you can call in 

1. jshell

 to show the status of your object for the OOP part.

**Comment by CalebLee** [comment]
Hello! Usually using javac helps in debugging because the error messages are really informative. For jshell, I'll usually write a jshell file (similar to those test1.jsh in each Lab) and edit that if I want to test specific cases or issues with my code, so it's more convenient when I want to debug.

Since plug-ins aren't allowed in PE it might be best to practise without them and use System.out.println() to check if parts of your code are running, as the other commenters have suggested!

**Comment by RussellDash332** [comment]
Since most of us are depending on jshell files at first to see if our code pass the test cases, there are several ways to do: (may include the ones mentioned above)
- add print statements somewhere inside the code
- check for the error message as Java will detect the line that causes it, **do not use jshell to debug but use javac**
- truncate some parts of the jsh files and see if you pass the first few statements. The downside of using tmux is that you cannot scroll along the long test cases from the jsh files and that's why truncating is also a viable strategy

**Comment by lulucopter** [comment]
A good practice I recommend is to break up your code into parts, and test them individually so we can ascertain where the error is coming from. Perhaps we can even use the `assert` function which was taught in lecture

**Comment by albertsutz** [comment]
I usually just javac every several lines. To make this quite fast, I do the ctrl-Z to interrupt the vim process and do javac <filename>.java. Afterwards, to go back to vim, just do `fg` and it will return the vim process back to the foreground. This is very fast because you can do it with just several steps.

**Comment by UnwilledTangent** [comment]
Thanks everyone for your comments!
