### ISSUE TITLE
How to pass level 6?

### ISSUE THREAD

**Issue by wjingen** [nus-cs2030/2122-s1#87]
# Summary

All my code works fine, just that I can't seem to pass CodeCrunch.

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

![image](https://user-images.githubusercontent.com/74229021/137200403-357956e5-1620-4e0d-bf0f-0168b2f17a40.png)
![image](https://user-images.githubusercontent.com/74229021/137200453-5911f30d-8e07-4965-87e1-23bbc14b1cfd.png)

Screenshots (if any)

**Comment by CalebLee** [comment]
Hello! The only issue I can think of right now might be that the file name isn't Main.java, or the file might not have been written/saved before you submitted to CodeCrunch? The snippet of code you screenshotted looks fine though, perhaps you could send a larger screenshot?

**Comment by cadencjk** [comment]
Could this be due to the fact that your Main class is not public? 
Instead of 
```ruby
class Main {
    //Your code
}
```
You can perhaps try 
```ruby
public class Main {
    //Your code
}
```
I don't think the public access modifier will affect anything, but maybe CodeCrunch only recognizes public class Main? Not sure but you can give it a shot if you have confirmed that your Main.java is spelled correctly.

**Comment by wjingen** [comment]
Hi all, really silly issue. I just resubmitted and the issue went away. Probably some glitch in Codecrunch. Thanks for your replies!!
